start_box = document.querySelector('.hit-me')
loading = document.querySelector('.loading')
practice = document.querySelector('.practice')
expanding = document.querySelector('.expanding')
event_box = document.querySelector('.event')
interactive = document.querySelector('.interactive')
sound = document.querySelector('.sound')
insect = document.querySelector('.insect')
nav = document.querySelector('.nav')
search = document.querySelector('.search')
relaxer = document.querySelector('.relaxer')
art = document.querySelector('.art')
btn = document.querySelector('.bg-music')


start_box.addEventListener('click', () => {
    start_box.classList.add('active')
    loading.classList.add('active')
    practice.classList.add('active')
    expanding.classList.add('active')
    event_box.classList.add('active')
    interactive.classList.add('active')
    sound.classList.add('active')
    insect.classList.add('active')
    nav.classList.add('active')
    search.classList.add('active')
    relaxer.classList.add('active')
    art.classList.add('active')
})

 btn.addEventListener('click', () => {
        document.querySelector('.bgMusic').play()
})
